# این فایل باید از extensions.db استفاده کند نه از یک db محلی
from app.extensions import db
from flask_login import UserMixin

# Import all models
from app.models.user import User
from app.models.department import Department
from app.models.unit import Unit
from app.models.workperiod import WorkPeriod
from app.models.personnel import Personnel
from app.models.personnelvalue import PersonnelValue
from app.models.dynamicfield import DynamicField
from app.models.unitpersonnelrequest import UnitPersonnelRequest
from app.models.personnelapprovalrequest import PersonnelApprovalRequest
from app.models.departmentmanager import DepartmentManager
from app.models.unitsupervisor import UnitSupervisor
from app.models.approvalrequest import ApprovalRequest
from app.models.setting import Setting
from app.models.exceltemplate import ExcelTemplate
from app.models.ticket import Ticket
from app.models.ticketreply import TicketReply
from app.models.userdocument import UserDocument
from app.models.request import Request
from app.models.personnelassignment import PersonnelAssignment
from app.models.personnelworkstatus import PersonnelWorkStatus
from app.models.workrevisionmessage import WorkRevisionMessage
from app.models.message import Message
from app.models.messagereply import MessageReply
from app.models.notification import Notification
from app.models.globalannouncement import GlobalAnnouncement
from app.models.activitylog import ActivityLog